/** AxaoHub design reminder: form controls feed a restaurant-quality live menu surface; no generic dashboard grid. */
import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { Check, Plus, QrCode, Trash2, Upload, WandSparkles } from "lucide-react";
import { Link } from "wouter";
import { AxaoShell, AdSlot, PremiumLink, ToolTop } from "@/components/AxaoShell";
import { MenuPreview } from "@/components/MenuPreview";
import { QrPanel } from "@/components/QrPanel";
import { decodeMenu, encodeMenu, sampleMenu, slugify, type MenuData } from "@/lib/menu";
import { useI18n } from "@/lib/i18n";
import { useSeo } from "@/lib/seo";

function uid() { return Math.random().toString(36).slice(2, 9); }
export default function MenuMaker() {
  const { t, locale } = useI18n(); useSeo("menu", locale); const [menu, setMenu] = useState<MenuData>(() => { const saved = localStorage.getItem("axaohub-menu"); return decodeMenu(saved) || sampleMenu; }); const [share, setShare] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => localStorage.setItem("axaohub-menu", encodeMenu(menu)), [menu]);
  const update = (patch: Partial<MenuData>) => setMenu((current) => ({ ...current, ...patch }));
  const updateCategory = (categoryId: string, patch: Partial<MenuData["categories"][number]>) => setMenu((current) => ({ ...current, categories: current.categories.map((category) => category.id === categoryId ? { ...category, ...patch } : category) }));
  const updateItem = (categoryId: string, itemId: string, patch: Record<string, string>) => setMenu((current) => ({ ...current, categories: current.categories.map((category) => category.id !== categoryId ? category : { ...category, items: category.items.map((item) => item.id === itemId ? { ...item, ...patch } : item) }) }));
  const createShare = () => { const data = encodeMenu({ ...menu, logo: undefined }); if (data.length > 3300) { setNotice(t("menu.shareWarning")); return; } const next = `${window.location.origin}/m/${slugify(menu.name)}?d=${encodeURIComponent(data)}`; setShare(next); navigator.clipboard.writeText(next); setNotice(t("tool.copied")); };
  const uploadLogo = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => update({ logo: String(reader.result) }); reader.readAsDataURL(file); };
  return <AxaoShell><main className="menu-maker-page"><ToolTop eyebrow={t("menu.eyebrow")} title={t("menu.title")} body={t("menu.body")}/><section className="menu-maker-layout"><div className="menu-editor"><div className="editor-card identity-card"><div className="editor-title"><span>01</span><div><h3>{t("menu.restaurant")}</h3><p>{t("menu.local")}</p></div></div><div className="identity-fields"><label>{t("menu.restaurant")}<input value={menu.name} onChange={(event) => update({ name: event.target.value })}/></label><label className="color-label">Accent<input type="color" value={menu.accent} onChange={(event) => update({ accent: event.target.value })}/></label><label className="upload-control"><Upload size={16}/><span>{t("menu.upload")}</span><input type="file" accept="image/*" onChange={uploadLogo}/></label></div></div>
    {menu.categories.map((category, categoryIndex) => <div className="editor-card category-editor" key={category.id}><div className="editor-title"><span>0{categoryIndex + 2}</span><div><h3>{t("menu.category")}</h3><p>{t("menu.item")}</p></div><button className="ghost-icon danger" onClick={() => setMenu((current) => ({ ...current, categories: current.categories.filter((entry) => entry.id !== category.id) }))}><Trash2 size={16}/></button></div><input className="category-name" value={category.name} onChange={(event) => updateCategory(category.id, { name: event.target.value })}/><div className="items-editor">{category.items.map((item) => <div className="menu-item-form" key={item.id}><div className="item-form-head"><span>{t("menu.item")}</span><button className="ghost-icon danger" onClick={() => setMenu((current) => ({ ...current, categories: current.categories.map((entry) => entry.id === category.id ? { ...entry, items: entry.items.filter((candidate) => candidate.id !== item.id) } : entry) }))}><Trash2 size={14}/></button></div><div className="item-fields"><input value={item.name} onChange={(event) => updateItem(category.id, item.id, { name: event.target.value })} placeholder={t("menu.name")}/><input value={item.price} onChange={(event) => updateItem(category.id, item.id, { price: event.target.value })} placeholder={t("menu.price")}/><input value={item.description} onChange={(event) => updateItem(category.id, item.id, { description: event.target.value })} placeholder={t("menu.description")}/></div></div>)}</div><button className="add-line" onClick={() => updateCategory(category.id, { items: [...category.items, { id: uid(), name: "", description: "", price: "" }] })}><Plus size={15}/>{t("menu.addItem")}</button></div>)}
    <button className="add-category" onClick={() => setMenu((current) => ({ ...current, categories: [...current.categories, { id: uid(), name: "New category", items: [{ id: uid(), name: "", description: "", price: "" }] }] }))}><Plus size={16}/>{t("menu.addCategory")}</button></div>
    <aside className="menu-preview-side"><div className="preview-title"><span>{t("menu.preview")}</span><i/></div><MenuPreview menu={menu}/><div className="menu-share-card"><div><QrCode size={20}/><span>{share ? t("tool.copied") : t("menu.publish")}</span></div><button onClick={createShare}><WandSparkles size={16}/>{t("menu.publish")}</button>{notice && <p>{notice}</p>}</div>{share && <div className="menu-qr"><QrPanel value={share} filename={`${slugify(menu.name)}-menu-qr`}/><Link className="open-shared" href={`/m/${slugify(menu.name)}?d=${encodeURIComponent(encodeMenu({ ...menu, logo: undefined }))}`}>{t("menu.open")} →</Link></div>}<PremiumLink/><p className="premium-note">{t("menu.premiumNote")}</p></aside>
  </section><AdSlot /></main></AxaoShell>;
}
